"""Add allergies and medications to UserDetails

Revision ID: 906c945c4861
Revises: 
Create Date: 2025-05-11 15:36:56.310604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906c945c4861'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allergies', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('medications', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.drop_column('medications')
        batch_op.drop_column('allergies')

    # ### end Alembic commands ###
